dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0 #importing from github to our brownie project
  - smartcontractkit/chainlink-brownie-contracts@1.0.2
compiler:
  solc:
    remappings: #Sto dicendo che quel import in AdvancdedCollectible.sol deve essere preso dalla dipendenza sopra
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.0.2'
wallets: # '$' means we get it from an environment variable
  from_key: ${PRIVATE_KEY}
networks:
  default: development
  rinkeby: #when we use the rinkeby chain of ethereum we are going to use specific addresses:
    vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 100000000000000000 #0.1 LINK

      